extends RefCounted
class_name LocalizationData

# AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
# Generated from res://localization/game_text.csv
# by res://scripts/tools/LocalizationDataGenerator.gd
# Regenerate with: godot --headless --script res://scripts/tools/GenerateLocalizationData.gd

static func get_translations() -> Dictionary:
	return {
		"en": {
			"ui.common.back": "Back",
			"ui.common.close": "Close",
			"ui.common.buy": "Buy",
			"ui.common.retry": "Retry",
			"ui.common.next": "Next",
			"ui.common.menu": "Menu",
			"ui.common.play": "Play",
			"ui.common.settings": "Settings",
			"ui.common.shop": "Shop",
			"ui.common.levels": "Levels",
			"ui.common.gold": "{gold}",
			"ui.common.gems": "{gems}",
			"ui.main.play": "Play",
			"ui.main.level_select": "Levels",
			"ui.main.shop": "Shop",
			"ui.main.settings": "Settings",
			"ui.shop.tab.boosters": "Boosters",
			"ui.shop.tab.gems": "Gems",
			"ui.shop.tab.bundles": "Bundles",
			"ui.shop.tab.offers": "Special",
			"ui.shop.feedback.purchased": "Purchased!",
			"ui.shop.feedback.not_enough_gold": "Not enough gold",
			"ui.shop.feedback.not_enough_gems": "Not enough gems",
			"ui.shop.feedback.payment_not_connected": "Payments are not connected yet",
			"ui.shop.feedback.item_unavailable": "Item unavailable",
			"ui.shop.feedback.purchase_failed": "Purchase failed",
			"ui.game.level": "Level {level}",
			"ui.game.moves": "Moves: {moves}",
			"ui.game.menu": "Menu",
			"ui.game.hp_value": "{current} / {max}",
			"ui.result.win": "Victory",
			"ui.result.retry": "Retry",
			"ui.result.next": "Next",
			"ui.result.menu": "Menu",
			"ui.result.reward.gold": "+{gold}",
			"ui.result.reward.gems": "+{gems}",
			"ui.result.reward.booster": "Booster received",
			"ui.result.reward.none": "No new rewards",
			"ui.lose_continue.title": "Defeat",
			"ui.lose_continue.description": "Continue with a booster?",
			"ui.lose_continue.watch_ad": "Watch",
			"ui.lose_continue.buy_moves": "5",
			"ui.lose_continue.close": "Close",
			"ui.lose_continue.not_enough_gems": "Not enough gems",
			"modifier.damage_color": "Damage color: {color}",
			"modifier.match_size_damage": "Match size damage",
			"modifier.extra_moves": "+{moves} extra moves",
			"color.red": "Red",
			"color.blue": "Blue",
			"color.green": "Green",
			"color.yellow": "Yellow",
			"color.purple": "Purple",
			"ui.settings.title": "Settings",
			"ui.settings.animations": "Animations",
			"ui.settings.reduced_motion": "Reduced Motion",
			"ui.settings.music": "Music",
			"ui.settings.sound_effects": "Sound Effects",
			"ui.level_select.zone_label": "Zone {index}: Levels {start}-{end}",
			"ui.level_select.start": "Start",
			"ui.shop.feedback.ad_not_connected": "Ads are not connected yet",
			"currency.gold": "Gold",
			"currency.gems": "Gems",
			"shop.price.label": "Price: {amount} {currency}",
			"shop.price.unavailable": "Price: not available",
			"shop.gives_label": "Gives: {items}",
			"modifier.color_generic": "Color",
			"shop.item.hammer": "Hammer",
			"shop.item.time_freeze": "Time Freeze",
			"shop.item.rocket_barrage": "Rocket Barrage",
			"booster.desc.hammer": "Clear a 3x3 area around one crystal.",
			"booster.desc.freeze_time": "The next 3 successful turns do not reduce moves.",
			"booster.desc.rocket_barrage": "Clear every crystal of the selected color.",
			"shop.item.booster_desc_gold": "Buy one {name} with gold.",
			"shop.item.booster_desc_gems": "Buy one {name} with gems.",
			"shop.item.gems_title": "{amount} Gems",
			"shop.item.gems_desc": "{amount} gems.",
			"shop.item.bundle_small": "Small Bundle",
			"shop.item.bundle_medium": "Medium Bundle",
			"shop.item.bundle_large": "Large Bundle",
			"shop.item.bundle_mega": "Mega Bundle",
			"shop.item.bundle_desc": "{gems} gems, {gold} gold, +{count} of every booster.",
			"shop.item.offer_watch_ad_title": "Ad",
			"shop.item.offer_watch_ad_desc": "Watch an ad for a free reward.",
			"shop.item.offer_gems_title": "Gems",
			"shop.item.offer_gems_desc": "Limited-time bonus gem offer.",
			"shop.item.offer_mega_gems_title": "Mega Gems",
			"shop.item.offer_mega_gems_desc": "The biggest bonus gem offer.",
			"shop.item.offer_boosters_title": "Boosters",
			"shop.item.offer_boosters_desc": "A pack of every booster.",
			"battle.hero.default": "Hero",
			"battle.hero.numbered": "Hero {n}",
			"battle.lane.left": "Left",
			"battle.lane.center": "Center",
			"battle.lane.right": "Right",
			"battle.lane.default": "Lane",
			"battle.damage.none": "No damage dealt",
			"battle.damage.single": "{hero} dealt {damage} damage",
			"battle.damage.multi": "{count} heroes attacked for {damage} total damage",
			"battle.damage.total": "Heroes dealt {damage} total damage",
			"battle.direct_damage.special": "Special cleared {count} tiles: {damage} damage",
			"battle.direct_damage.match_multiplier": "Matched {count} {color} tiles x{multiplier}: {damage} damage",
			"battle.direct_damage.cleared": "Cleared {count} tiles: {damage} damage",
			"battle.direct_damage.matched": "Matched {count} tiles: {damage} damage",
			"battle.enemy.defeated": "Enemy defeated!",
			"battle.lane_activation.single": "{lane} lane activated",
			"battle.lane_activation.multi": "{count} lanes activated",
			"battle.special.combo": "Special combo cleared {count} tiles",
			"battle.special.activated_generic": "Specials activated",
			"battle.special.single_cleared": "{special} cleared {count} tiles",
			"battle.special.single_activated": "{special} activated",
			"battle.enemy_action.preparing": "Enemy is preparing an attack",
			"battle.enemy_action.attacked": "Enemy attacked {hero} for {damage} damage",
			"battle.invalid_swap.no_match": "Swap must create a match",
			"battle.invalid_swap.not_neighbor": "Choose a neighboring tile",
			"battle.invalid_swap.frozen": "Frozen cells cannot be swapped.",
			"battle.invalid_swap.generic": "That swap doesn't work",
			"battle.invalid_input.swipe_short": "Swipe a little farther",
			"battle.invalid_input.out_of_bounds": "Stay inside the board",
			"battle.invalid_input.turn_busy": "Wait until the turn finishes",
			"battle.invalid_input.generic": "Invalid input",
			"battle.ability.start_generic": "Ability activated",
			"battle.ability.start_named": "{hero} activated",
			"battle.ability.rejected_not_ready": "Ability is not ready yet",
			"battle.ability.rejected_hero_down": "This hero is down",
			"battle.ability.rejected_battle_over": "Battle is already over",
			"battle.ability.rejected_generic": "Ability unavailable",
			"battle.result.victory": "Victory! Progress saved ({stars}/3 stars)",
			"battle.result.defeat": "Defeat: use boosted colors, special tiles, and better matches",
			"battle.special.line": "Line special",
			"battle.special.bomb": "Color bomb",
			"battle.special.generic": "Special tile",
			"ui.orientation.rotate_device": "Please rotate your device",
		},
		"ru": {
			"ui.common.back": "Назад",
			"ui.common.close": "Закрыть",
			"ui.common.buy": "Купить",
			"ui.common.retry": "Повторить",
			"ui.common.next": "Далее",
			"ui.common.menu": "Меню",
			"ui.common.play": "Играть",
			"ui.common.settings": "Настройки",
			"ui.common.shop": "Магазин",
			"ui.common.levels": "Уровни",
			"ui.common.gold": "{gold}",
			"ui.common.gems": "{gems}",
			"ui.main.play": "Играть",
			"ui.main.level_select": "Уровни",
			"ui.main.shop": "Магазин",
			"ui.main.settings": "Настройки",
			"ui.shop.tab.boosters": "Бустеры",
			"ui.shop.tab.gems": "Гемы",
			"ui.shop.tab.bundles": "Пакеты",
			"ui.shop.tab.offers": "Спец",
			"ui.shop.feedback.purchased": "Куплено!",
			"ui.shop.feedback.not_enough_gold": "Недостаточно золота",
			"ui.shop.feedback.not_enough_gems": "Недостаточно гемов",
			"ui.shop.feedback.payment_not_connected": "Платежи пока не подключены",
			"ui.shop.feedback.item_unavailable": "Товар недоступен",
			"ui.shop.feedback.purchase_failed": "Покупка не удалась",
			"ui.game.level": "Уровень {level}",
			"ui.game.moves": "Ходы: {moves}",
			"ui.game.menu": "Меню",
			"ui.game.hp_value": "{current} / {max}",
			"ui.result.win": "Победа",
			"ui.result.retry": "Повторить",
			"ui.result.next": "Далее",
			"ui.result.menu": "Меню",
			"ui.result.reward.gold": "+{gold}",
			"ui.result.reward.gems": "+{gems}",
			"ui.result.reward.booster": "Получен бустер",
			"ui.result.reward.none": "Новых наград нет",
			"ui.lose_continue.title": "Поражение",
			"ui.lose_continue.description": "Продолжить с бустером?",
			"ui.lose_continue.watch_ad": "Смотреть",
			"ui.lose_continue.buy_moves": "5",
			"ui.lose_continue.close": "Закрыть",
			"ui.lose_continue.not_enough_gems": "Недостаточно гемов",
			"modifier.damage_color": "Цвет урона: {color}",
			"modifier.match_size_damage": "Урон за размер комбо",
			"modifier.extra_moves": "+{moves} доп. ходов",
			"color.red": "Красный",
			"color.blue": "Синий",
			"color.green": "Зелёный",
			"color.yellow": "Жёлтый",
			"color.purple": "Фиолетовый",
			"ui.settings.title": "Настройки",
			"ui.settings.animations": "Анимации",
			"ui.settings.reduced_motion": "Уменьшенная анимация",
			"ui.settings.music": "Музыка",
			"ui.settings.sound_effects": "Звуковые эффекты",
			"ui.level_select.zone_label": "Зона {index}: Уровни {start}-{end}",
			"ui.level_select.start": "Начать",
			"ui.shop.feedback.ad_not_connected": "Реклама пока не подключена",
			"currency.gold": "Золото",
			"currency.gems": "Гемы",
			"shop.price.label": "Цена: {amount} {currency}",
			"shop.price.unavailable": "Цена: недоступна",
			"shop.gives_label": "Даёт: {items}",
			"modifier.color_generic": "Цвет",
			"shop.item.hammer": "Молот",
			"shop.item.time_freeze": "Заморозка времени",
			"shop.item.rocket_barrage": "Ракетный залп",
			"booster.desc.hammer": "Очищает область 3x3 вокруг одного кристалла.",
			"booster.desc.freeze_time": "Следующие 3 успешных хода не уменьшают количество ходов.",
			"booster.desc.rocket_barrage": "Очищает все кристаллы выбранного цвета.",
			"shop.item.booster_desc_gold": "Купить один {name} за золото.",
			"shop.item.booster_desc_gems": "Купить один {name} за гемы.",
			"shop.item.gems_title": "{amount} гемов",
			"shop.item.gems_desc": "{amount} гемов.",
			"shop.item.bundle_small": "Малый набор",
			"shop.item.bundle_medium": "Средний набор",
			"shop.item.bundle_large": "Большой набор",
			"shop.item.bundle_mega": "Мега набор",
			"shop.item.bundle_desc": "{gems} гемов, {gold} золота, +{count} каждого бустера.",
			"shop.item.offer_watch_ad_title": "Реклама",
			"shop.item.offer_watch_ad_desc": "Посмотрите рекламу за бесплатную награду.",
			"shop.item.offer_gems_title": "Гемы",
			"shop.item.offer_gems_desc": "Ограниченное по времени предложение бонусных гемов.",
			"shop.item.offer_mega_gems_title": "Мега гемы",
			"shop.item.offer_mega_gems_desc": "Самое большое предложение бонусных гемов.",
			"shop.item.offer_boosters_title": "Бустеры",
			"shop.item.offer_boosters_desc": "Набор всех бустеров.",
			"battle.hero.default": "Герой",
			"battle.hero.numbered": "Герой {n}",
			"battle.lane.left": "Левая",
			"battle.lane.center": "Центральная",
			"battle.lane.right": "Правая",
			"battle.lane.default": "Линия",
			"battle.damage.none": "Урон не нанесён",
			"battle.damage.single": "{hero} нанёс {damage} урона",
			"battle.damage.multi": "{count} героев атаковали и нанесли {damage} урона",
			"battle.damage.total": "Герои нанесли {damage} урона",
			"battle.direct_damage.special": "Спецплитка очистила {count} клеток: {damage} урона",
			"battle.direct_damage.match_multiplier": "Совпадение {count} {color} плиток x{multiplier}: {damage} урона",
			"battle.direct_damage.cleared": "Очищено {count} клеток: {damage} урона",
			"battle.direct_damage.matched": "Совпадение {count} клеток: {damage} урона",
			"battle.enemy.defeated": "Враг повержен!",
			"battle.lane_activation.single": "Линия {lane} активирована",
			"battle.lane_activation.multi": "{count} линий активировано",
			"battle.special.combo": "Спецкомбо очистило {count} клеток",
			"battle.special.activated_generic": "Спецплитки активированы",
			"battle.special.single_cleared": "{special} очистила {count} клеток",
			"battle.special.single_activated": "{special} активирована",
			"battle.enemy_action.preparing": "Враг готовит атаку",
			"battle.enemy_action.attacked": "Враг атаковал {hero} и нанёс {damage} урона",
			"battle.invalid_swap.no_match": "Обмен должен создать совпадение",
			"battle.invalid_swap.not_neighbor": "Выберите соседнюю клетку",
			"battle.invalid_swap.frozen": "Замороженные клетки нельзя менять местами.",
			"battle.invalid_swap.generic": "Этот обмен невозможен",
			"battle.invalid_input.swipe_short": "Проведите чуть дальше",
			"battle.invalid_input.out_of_bounds": "Оставайтесь в пределах поля",
			"battle.invalid_input.turn_busy": "Дождитесь завершения хода",
			"battle.invalid_input.generic": "Некорректный ввод",
			"battle.ability.start_generic": "Способность активирована",
			"battle.ability.start_named": "{hero} активировал способность",
			"battle.ability.rejected_not_ready": "Способность ещё не готова",
			"battle.ability.rejected_hero_down": "Этот герой повержен",
			"battle.ability.rejected_battle_over": "Бой уже завершён",
			"battle.ability.rejected_generic": "Способность недоступна",
			"battle.result.victory": "Победа! Прогресс сохранён ({stars}/3 звёзд)",
			"battle.result.defeat": "Поражение: используйте усиленные цвета, спецплитки и более крупные совпадения",
			"battle.special.line": "Линейная спецплитка",
			"battle.special.bomb": "Цветовая бомба",
			"battle.special.generic": "Спецплитка",
			"ui.orientation.rotate_device": "Поверните устройство",
		},
	}
