extends RefCounted
class_name LocalizationData

# AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
# Generated from res://localization/game_text.csv
# by res://scripts/tools/LocalizationDataGenerator.gd
# Regenerate with: godot --headless --script res://scripts/tools/GenerateLocalizationData.gd

static func get_translations() -> Dictionary:
	return {
		"en": {
			"ui.common.back": "Back",
			"ui.common.close": "Close",
			"ui.common.buy": "Buy",
			"ui.common.retry": "Retry",
			"ui.common.next": "Next",
			"ui.common.menu": "Menu",
			"ui.common.play": "Play",
			"ui.common.settings": "Settings",
			"ui.common.shop": "Shop",
			"ui.common.levels": "Levels",
			"ui.common.gold": "Gold: {gold}",
			"ui.common.gems": "Gems: {gems}",
			"ui.main.play": "Play",
			"ui.main.level_select": "Level Select",
			"ui.main.shop": "Shop",
			"ui.main.settings": "Settings",
			"ui.shop.tab.boosters": "Boosters",
			"ui.shop.tab.gems": "Gems",
			"ui.shop.tab.bundles": "Bundles",
			"ui.shop.tab.offers": "Offers",
			"ui.shop.feedback.purchased": "Purchased!",
			"ui.shop.feedback.not_enough_gold": "Not enough gold",
			"ui.shop.feedback.not_enough_gems": "Not enough gems",
			"ui.shop.feedback.payment_not_connected": "Payments are not connected yet",
			"ui.shop.feedback.item_unavailable": "Item unavailable",
			"ui.shop.feedback.purchase_failed": "Purchase failed",
			"ui.game.level": "Level {level}",
			"ui.game.moves": "Moves: {moves}",
			"ui.game.menu": "Menu",
			"ui.game.hp_value": "{current} / {max}",
			"ui.result.win": "Victory",
			"ui.result.lose": "Defeat",
			"ui.result.retry": "Retry",
			"ui.result.next": "Next",
			"ui.result.menu": "Menu",
			"ui.result.reward.unlocked_next_level": "Unlocked next level",
			"ui.result.reward.gold": "+{gold} Gold",
			"ui.result.reward.booster": "Random booster received",
			"ui.lose_continue.title": "Defeat",
			"ui.lose_continue.description": "Continue with a booster?",
			"ui.lose_continue.watch_ad": "Watch Ad",
			"ui.lose_continue.buy_moves": "Buy Moves",
			"ui.lose_continue.close": "Close",
			"ui.lose_continue.not_enough_gems": "Not enough gems",
			"modifier.damage_color": "Damage color: {color}",
			"modifier.match_size_damage": "Match size damage",
			"modifier.extra_moves": "+{moves} extra moves",
			"color.red": "Red",
			"color.blue": "Blue",
			"color.green": "Green",
			"color.yellow": "Yellow",
			"color.purple": "Purple",
			"ui.settings.title": "Settings",
			"ui.settings.animations": "Animations",
			"ui.settings.reduced_motion": "Reduced Motion",
			"ui.settings.music": "Music",
			"ui.settings.sound_effects": "Sound Effects",
		},
		"ru": {
			"ui.common.back": "Назад",
			"ui.common.close": "Закрыть",
			"ui.common.buy": "Купить",
			"ui.common.retry": "Повторить",
			"ui.common.next": "Далее",
			"ui.common.menu": "Меню",
			"ui.common.play": "Играть",
			"ui.common.settings": "Настройки",
			"ui.common.shop": "Магазин",
			"ui.common.levels": "Уровни",
			"ui.common.gold": "Золото: {gold}",
			"ui.common.gems": "Гемы: {gems}",
			"ui.main.play": "Играть",
			"ui.main.level_select": "Выбрать уровень",
			"ui.main.shop": "Магазин",
			"ui.main.settings": "Настройки",
			"ui.shop.tab.boosters": "Бустеры",
			"ui.shop.tab.gems": "Гемы",
			"ui.shop.tab.bundles": "Пакеты",
			"ui.shop.tab.offers": "Предложения",
			"ui.shop.feedback.purchased": "Куплено!",
			"ui.shop.feedback.not_enough_gold": "Недостаточно золота",
			"ui.shop.feedback.not_enough_gems": "Недостаточно гемов",
			"ui.shop.feedback.payment_not_connected": "Платежи пока не подключены",
			"ui.shop.feedback.item_unavailable": "Товар недоступен",
			"ui.shop.feedback.purchase_failed": "Покупка не удалась",
			"ui.game.level": "Уровень {level}",
			"ui.game.moves": "Ходы: {moves}",
			"ui.game.menu": "Меню",
			"ui.game.hp_value": "{current} / {max}",
			"ui.result.win": "Победа",
			"ui.result.lose": "Поражение",
			"ui.result.retry": "Повторить",
			"ui.result.next": "Далее",
			"ui.result.menu": "Меню",
			"ui.result.reward.unlocked_next_level": "Открыт следующий уровень",
			"ui.result.reward.gold": "+{gold} золота",
			"ui.result.reward.booster": "Получен случайный бустер",
			"ui.lose_continue.title": "Поражение",
			"ui.lose_continue.description": "Продолжить с бустером?",
			"ui.lose_continue.watch_ad": "Смотреть рекламу",
			"ui.lose_continue.buy_moves": "Купить ходы",
			"ui.lose_continue.close": "Закрыть",
			"ui.lose_continue.not_enough_gems": "Недостаточно гемов",
			"modifier.damage_color": "Цвет урона: {color}",
			"modifier.match_size_damage": "Урон за размер комбо",
			"modifier.extra_moves": "+{moves} доп. ходов",
			"color.red": "Красный",
			"color.blue": "Синий",
			"color.green": "Зелёный",
			"color.yellow": "Жёлтый",
			"color.purple": "Фиолетовый",
			"ui.settings.title": "Настройки",
			"ui.settings.animations": "Анимации",
			"ui.settings.reduced_motion": "Уменьшенная анимация",
			"ui.settings.music": "Музыка",
			"ui.settings.sound_effects": "Звуковые эффекты",
		},
	}
